import { Book, LanguageCode } from './types';

// A curated list of 100 influential books.
export const BOOKS: Book[] = [
  { id: '1', title: 'Meditations', author: 'Marcus Aurelius', year: 180, tags: ['Philosophy', 'Stoicism'] },
  { id: '2', title: 'The Prince', author: 'Niccolò Machiavelli', year: 1532, tags: ['Politics', 'Philosophy'] },
  { id: '3', title: '1984', author: 'George Orwell', year: 1949, tags: ['Fiction', 'Dystopian'] },
  { id: '4', title: 'Sapiens: A Brief History of Humankind', author: 'Yuval Noah Harari', year: 2011, tags: ['History', 'Anthropology'] },
  { id: '5', title: 'The Art of War', author: 'Sun Tzu', year: -500, tags: ['Strategy', 'Philosophy'] },
  { id: '6', title: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', year: 2011, tags: ['Psychology', 'Economics'] },
  { id: '7', title: 'The Republic', author: 'Plato', year: -375, tags: ['Philosophy', 'Politics'] },
  { id: '8', title: 'Atomic Habits', author: 'James Clear', year: 2018, tags: ['Self-Help', 'Psychology'] },
  { id: '9', title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', year: 1925, tags: ['Fiction', 'Classic'] },
  { id: '10', title: 'Tao Te Ching', author: 'Laozi', year: -400, tags: ['Philosophy', 'Spirituality'] },
  { id: '11', title: 'Man’s Search for Meaning', author: 'Viktor Frankl', year: 1946, tags: ['Psychology', 'Memoir'] },
  { id: '12', title: 'Brave New World', author: 'Aldous Huxley', year: 1932, tags: ['Fiction', 'Dystopian'] },
  { id: '13', title: 'The Alchemist', author: 'Paulo Coelho', year: 1988, tags: ['Fiction', 'Spirituality'] },
  { id: '14', title: 'Pride and Prejudice', author: 'Jane Austen', year: 1813, tags: ['Fiction', 'Romance'] },
  { id: '15', title: 'To Kill a Mockingbird', author: 'Harper Lee', year: 1960, tags: ['Fiction', 'Classic'] },
  { id: '16', title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', year: 1866, tags: ['Fiction', 'Psychological'] },
  { id: '17', title: 'The Wealth of Nations', author: 'Adam Smith', year: 1776, tags: ['Economics', 'History'] },
  { id: '18', title: 'The Origin of Species', author: 'Charles Darwin', year: 1859, tags: ['Science', 'Biology'] },
  { id: '19', title: 'The Prophet', author: 'Kahlil Gibran', year: 1923, tags: ['Poetry', 'Philosophy'] },
  { id: '20', title: 'Guns, Germs, and Steel', author: 'Jared Diamond', year: 1997, tags: ['History', 'Anthropology'] },
  { id: '21', title: 'A Tale of Two Cities', author: 'Charles Dickens', year: 1859, tags: ['Fiction', 'Historical'] },
  { id: '22', title: 'The Little Prince', author: 'Antoine de Saint-Exupéry', year: 1943, tags: ['Fiction', 'Philosophy'] },
  { id: '23', title: 'Don Quixote', author: 'Miguel de Cervantes', year: 1605, tags: ['Fiction', 'Adventure'] },
  { id: '24', title: 'One Hundred Years of Solitude', author: 'Gabriel García Márquez', year: 1967, tags: ['Fiction', 'Magical Realism'] },
  { id: '25', title: 'Moby Dick', author: 'Herman Melville', year: 1851, tags: ['Fiction', 'Adventure'] },
  { id: '26', title: 'War and Peace', author: 'Leo Tolstoy', year: 1869, tags: ['Fiction', 'Historical'] },
  { id: '27', title: 'The Odyssey', author: 'Homer', year: -800, tags: ['Poetry', 'Mythology'] },
  { id: '28', title: 'Ulysses', author: 'James Joyce', year: 1922, tags: ['Fiction', 'Modernist'] },
  { id: '29', title: 'The Divine Comedy', author: 'Dante Alighieri', year: 1320, tags: ['Poetry', 'Classic'] },
  { id: '30', title: 'The Brothers Karamazov', author: 'Fyodor Dostoevsky', year: 1880, tags: ['Fiction', 'Philosophical'] },
  { id: '31', title: 'Hamlet', author: 'William Shakespeare', year: 1603, tags: ['Drama', 'Tragedy'] },
  { id: '32', title: 'The Catcher in the Rye', author: 'J.D. Salinger', year: 1951, tags: ['Fiction', 'Coming-of-age'] },
  { id: '33', title: 'Wuthering Heights', author: 'Emily Brontë', year: 1847, tags: ['Fiction', 'Gothic'] },
  { id: '34', title: 'Jane Eyre', author: 'Charlotte Brontë', year: 1847, tags: ['Fiction', 'Romance'] },
  { id: '35', title: 'The Adventures of Huckleberry Finn', author: 'Mark Twain', year: 1884, tags: ['Fiction', 'Satire'] },
  { id: '36', title: 'The Iliad', author: 'Homer', year: -750, tags: ['Poetry', 'Mythology'] },
  { id: '37', title: 'Lolita', author: 'Vladimir Nabokov', year: 1955, tags: ['Fiction', 'Modernist'] },
  { id: '38', title: 'Catch-22', author: 'Joseph Heller', year: 1961, tags: ['Fiction', 'Satire'] },
  { id: '39', title: 'Alice’s Adventures in Wonderland', author: 'Lewis Carroll', year: 1865, tags: ['Fiction', 'Fantasy'] },
  { id: '40', title: 'Frankenstein', author: 'Mary Shelley', year: 1818, tags: ['Fiction', 'Horror'] },
  { id: '41', title: 'The Grapes of Wrath', author: 'John Steinbeck', year: 1939, tags: ['Fiction', 'Historical'] },
  { id: '42', title: 'Slaughterhouse-Five', author: 'Kurt Vonnegut', year: 1969, tags: ['Fiction', 'Sci-Fi'] },
  { id: '43', title: 'Fahrenheit 451', author: 'Ray Bradbury', year: 1953, tags: ['Fiction', 'Dystopian'] },
  { id: '44', title: 'Lord of the Flies', author: 'William Golding', year: 1954, tags: ['Fiction', 'Allegory'] },
  { id: '45', title: 'The Stranger', author: 'Albert Camus', year: 1942, tags: ['Fiction', 'Philosophy'] },
  { id: '46', title: 'Anna Karenina', author: 'Leo Tolstoy', year: 1877, tags: ['Fiction', 'Romance'] },
  { id: '47', title: 'Heart of Darkness', author: 'Joseph Conrad', year: 1899, tags: ['Fiction', 'Adventure'] },
  { id: '48', title: 'Dracula', author: 'Bram Stoker', year: 1897, tags: ['Fiction', 'Horror'] },
  { id: '49', title: 'The Handmaid’s Tale', author: 'Margaret Atwood', year: 1985, tags: ['Fiction', 'Dystopian'] },
  { id: '50', title: 'Beloved', author: 'Toni Morrison', year: 1987, tags: ['Fiction', 'Historical'] },
  { id: '51', title: 'Invisible Man', author: 'Ralph Ellison', year: 1952, tags: ['Fiction', 'Social'] },
  { id: '52', title: 'To the Lighthouse', author: 'Virginia Woolf', year: 1927, tags: ['Fiction', 'Modernist'] },
  { id: '53', title: 'The Count of Monte Cristo', author: 'Alexandre Dumas', year: 1844, tags: ['Fiction', 'Adventure'] },
  { id: '54', title: 'Les Misérables', author: 'Victor Hugo', year: 1862, tags: ['Fiction', 'Historical'] },
  { id: '55', title: 'Great Expectations', author: 'Charles Dickens', year: 1861, tags: ['Fiction', 'Classic'] },
  { id: '56', title: 'Middlemarch', author: 'George Eliot', year: 1871, tags: ['Fiction', 'Realism'] },
  { id: '57', title: 'Mrs. Dalloway', author: 'Virginia Woolf', year: 1925, tags: ['Fiction', 'Modernist'] },
  { id: '58', title: 'Things Fall Apart', author: 'Chinua Achebe', year: 1958, tags: ['Fiction', 'Historical'] },
  { id: '59', title: 'The Sun Also Rises', author: 'Ernest Hemingway', year: 1926, tags: ['Fiction', 'Modernist'] },
  { id: '60', title: 'On the Road', author: 'Jack Kerouac', year: 1957, tags: ['Fiction', 'Beat'] },
  { id: '61', title: 'The Bell Jar', author: 'Sylvia Plath', year: 1963, tags: ['Fiction', 'Semi-autobiographical'] },
  { id: '62', title: 'Dune', author: 'Frank Herbert', year: 1965, tags: ['Sci-Fi', 'Epic'] },
  { id: '63', title: 'The Hobbit', author: 'J.R.R. Tolkien', year: 1937, tags: ['Fantasy', 'Adventure'] },
  { id: '64', title: 'The Lord of the Rings', author: 'J.R.R. Tolkien', year: 1954, tags: ['Fantasy', 'Epic'] },
  { id: '65', title: 'Animal Farm', author: 'George Orwell', year: 1945, tags: ['Fiction', 'Satire'] },
  { id: '66', title: 'Gone with the Wind', author: 'Margaret Mitchell', year: 1936, tags: ['Fiction', 'Historical'] },
  { id: '67', title: 'The Old Man and the Sea', author: 'Ernest Hemingway', year: 1952, tags: ['Fiction', 'Literary'] },
  { id: '68', title: 'Of Mice and Men', author: 'John Steinbeck', year: 1937, tags: ['Fiction', 'Tragedy'] },
  { id: '69', title: 'A Farewell to Arms', author: 'Ernest Hemingway', year: 1929, tags: ['Fiction', 'War'] },
  { id: '70', title: 'Rebecca', author: 'Daphne du Maurier', year: 1938, tags: ['Fiction', 'Gothic'] },
  { id: '71', title: 'The Picture of Dorian Gray', author: 'Oscar Wilde', year: 1890, tags: ['Fiction', 'Philosophical'] },
  { id: '72', title: 'Siddhartha', author: 'Hermann Hesse', year: 1922, tags: ['Fiction', 'Spirituality'] },
  { id: '73', title: 'Candide', author: 'Voltaire', year: 1759, tags: ['Fiction', 'Satire'] },
  { id: '74', title: 'Faust', author: 'Johann Wolfgang von Goethe', year: 1808, tags: ['Drama', 'Tragedy'] },
  { id: '75', title: 'Madame Bovary', author: 'Gustave Flaubert', year: 1856, tags: ['Fiction', 'Realism'] },
  { id: '76', title: 'The Metamorphosis', author: 'Franz Kafka', year: 1915, tags: ['Fiction', 'Absurdist'] },
  { id: '77', title: 'In Search of Lost Time', author: 'Marcel Proust', year: 1913, tags: ['Fiction', 'Modernist'] },
  { id: '78', title: 'Midnight’s Children', author: 'Salman Rushdie', year: 1981, tags: ['Fiction', 'Magical Realism'] },
  { id: '79', title: 'Life of Pi', author: 'Yann Martel', year: 2001, tags: ['Fiction', 'Adventure'] },
  { id: '80', title: 'A Clockwork Orange', author: 'Anthony Burgess', year: 1962, tags: ['Fiction', 'Dystopian'] },
  { id: '81', title: 'Cosmos', author: 'Carl Sagan', year: 1980, tags: ['Science', 'Astronomy'] },
  { id: '82', title: 'A Brief History of Time', author: 'Stephen Hawking', year: 1988, tags: ['Science', 'Physics'] },
  { id: '83', title: 'Silent Spring', author: 'Rachel Carson', year: 1962, tags: ['Science', 'Environment'] },
  { id: '84', title: 'The Selfish Gene', author: 'Richard Dawkins', year: 1976, tags: ['Science', 'Biology'] },
  { id: '85', title: 'Principia Mathematica', author: 'Isaac Newton', year: 1687, tags: ['Science', 'Physics'] },
  { id: '86', title: 'Structure of Scientific Revolutions', author: 'Thomas Kuhn', year: 1962, tags: ['Philosophy', 'Science'] },
  { id: '87', title: 'Critique of Pure Reason', author: 'Immanuel Kant', year: 1781, tags: ['Philosophy', 'Metaphysics'] },
  { id: '88', title: 'Being and Time', author: 'Martin Heidegger', year: 1927, tags: ['Philosophy', 'Existentialism'] },
  { id: '89', title: 'Thus Spoke Zarathustra', author: 'Friedrich Nietzsche', year: 1883, tags: ['Philosophy', 'Existentialism'] },
  { id: '90', title: 'Leviathan', author: 'Thomas Hobbes', year: 1651, tags: ['Politics', 'Philosophy'] },
  { id: '91', title: 'The Social Contract', author: 'Jean-Jacques Rousseau', year: 1762, tags: ['Politics', 'Philosophy'] },
  { id: '92', title: 'Das Kapital', author: 'Karl Marx', year: 1867, tags: ['Politics', 'Economics'] },
  { id: '93', title: 'The Interpretation of Dreams', author: 'Sigmund Freud', year: 1899, tags: ['Psychology', 'Psychoanalysis'] },
  { id: '94', title: 'The Second Sex', author: 'Simone de Beauvoir', year: 1949, tags: ['Philosophy', 'Feminism'] },
  { id: '95', title: 'Orientalism', author: 'Edward Said', year: 1978, tags: ['History', 'Postcolonialism'] },
  { id: '96', title: 'Manufacturing Consent', author: 'Noam Chomsky', year: 1988, tags: ['Politics', 'Media'] },
  { id: '97', title: 'The Diary of a Young Girl', author: 'Anne Frank', year: 1947, tags: ['Memoir', 'Historical'] },
  { id: '98', title: 'I Know Why the Caged Bird Sings', author: 'Maya Angelou', year: 1969, tags: ['Memoir', 'Autobiography'] },
  { id: '99', title: 'Long Walk to Freedom', author: 'Nelson Mandela', year: 1994, tags: ['Memoir', 'Political'] },
  { id: '100', title: 'The Autobiography of Malcolm X', author: 'Malcolm X', year: 1965, tags: ['Memoir', 'Political'] },
];

export const AI_MODEL_TEXT = 'gemini-3-flash-preview';

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    library: "Library",
    startReading: "Start Reading (5 min)",
    dailyPick: "Daily Pick",
    wisdomInbox: "Wisdom in your Inbox",
    subscribeDesc: "Get the daily book summary delivered straight to your email every morning. Start your day with perspective.",
    subscribed: "You're on the list! See you tomorrow.",
    subscribe: "Subscribe",
    back: "Back",
    summaryOf: "A 5-minute summary of",
    by: "By",
    keyInsights: "Key Insights",
    notableQuotes: "Notable Quotes",
    finalThought: "Final Thought",
    markAsRead: "Mark as Read",
    wisdomAcquired: "Wisdom Acquired",
    completedMsg: "You've completed the summary for",
    shareWisdom: "Share Wisdom",
    nextRead: "Next Read Available In",
    volumes: "volumes",
    returnHome: "Return Home",
    errorMsg: "Unable to retrieve the book's wisdom at this moment. Please try again later.",
    brewing: "Brewing your daily wisdom...",
    emailPlaceholder: "your@email.com",
    readSummary: "Read Summary"
  },
  zh: {
    library: "图书馆",
    startReading: "开始阅读 (5分钟)",
    dailyPick: "每日精选",
    wisdomInbox: "智慧订阅",
    subscribeDesc: "每天早上直接将书籍摘要发送到您的邮箱。用全新的视角开启一天。",
    subscribed: "已订阅！明天见。",
    subscribe: "订阅",
    back: "返回",
    summaryOf: "5分钟摘要：",
    by: "作者：",
    keyInsights: "核心洞察",
    notableQuotes: "经典名言",
    finalThought: "结语",
    markAsRead: "标记为已读",
    wisdomAcquired: "智慧已获取",
    completedMsg: "您已完成阅读摘要：",
    shareWisdom: "分享智慧",
    nextRead: "下一次阅读将于",
    volumes: "卷",
    returnHome: "返回首页",
    errorMsg: "此刻无法获取智慧摘要。请稍后再试。",
    brewing: "正在酝酿您的每日智慧...",
    emailPlaceholder: "您的邮箱地址",
    readSummary: "阅读摘要"
  },
  es: {
    library: "Biblioteca",
    startReading: "Empezar a leer (5 min)",
    dailyPick: "Selección Diaria",
    wisdomInbox: "Sabiduría en tu bandeja",
    subscribeDesc: "Recibe el resumen diario del libro directamente en tu correo cada mañana. Comienza tu día con perspectiva.",
    subscribed: "¡Estás en la lista! Hasta mañana.",
    subscribe: "Suscribirse",
    back: "Atrás",
    summaryOf: "Resumen de 5 minutos de",
    by: "Por",
    keyInsights: "Ideas Clave",
    notableQuotes: "Citas Notables",
    finalThought: "Pensamiento Final",
    markAsRead: "Marcar como leído",
    wisdomAcquired: "Sabiduría Adquirida",
    completedMsg: "Has completado el resumen de",
    shareWisdom: "Compartir Sabiduría",
    nextRead: "Próxima lectura disponible en",
    volumes: "volúmenes",
    returnHome: "Volver al Inicio",
    errorMsg: "No se puede recuperar la sabiduría del libro en este momento. Inténtalo de nuevo más tarde.",
    brewing: "Preparando tu sabiduría diaria...",
    emailPlaceholder: "tu@correo.com",
    readSummary: "Leer Resumen"
  },
  hi: {
    library: "पुस्तकालय",
    startReading: "पढ़ना शुरू करें (5 मिनट)",
    dailyPick: "दैनिक चयन",
    wisdomInbox: "आपके इनबॉक्स में ज्ञान",
    subscribeDesc: "हर सुबह सीधे अपने ईमेल पर दैनिक पुस्तक सारांश प्राप्त करें। अपने दिन की शुरुआत परिप्रेक्ष्य के साथ करें।",
    subscribed: "आप सूची में हैं! कल मिलते हैं।",
    subscribe: "सदस्यता लें",
    back: "वापस",
    summaryOf: "5 मिनट का सारांश",
    by: "लेखक:",
    keyInsights: "मुख्य अंतर्दृष्टि",
    notableQuotes: "उल्लेखनीय उद्धरण",
    finalThought: "अंतिम विचार",
    markAsRead: "पढ़ा हुआ चिह्नित करें",
    wisdomAcquired: "ज्ञान प्राप्त किया",
    completedMsg: "आपने सारांश पूरा कर लिया है:",
    shareWisdom: "ज्ञान साझा करें",
    nextRead: "अगला पाठ उपलब्ध होगा",
    volumes: "किताबें",
    returnHome: "घर लौटें",
    errorMsg: "इस समय पुस्तक का ज्ञान प्राप्त करने में असमर्थ। कृपया बाद में पुनः प्रयास करें।",
    brewing: "आपका दैनिक ज्ञान तैयार हो रहा है...",
    emailPlaceholder: "आपका@ईमेल.com",
    readSummary: "सारांश पढ़ें"
  },
  ar: {
    library: "المكتبة",
    startReading: "ابدأ القراءة (5 دقائق)",
    dailyPick: "اختيار اليوم",
    wisdomInbox: "الحكمة في بريدك الوارد",
    subscribeDesc: "احصل على ملخص الكتاب اليومي مباشرة إلى بريدك الإلكتروني كل صباح. ابدأ يومك بمنظور جديد.",
    subscribed: "أنت في القائمة! نراكم غدا.",
    subscribe: "اشتراك",
    back: "عودة",
    summaryOf: "ملخص في 5 دقائق لـ",
    by: "بواسطة",
    keyInsights: "رؤى رئيسية",
    notableQuotes: "اقتباسات بارزة",
    finalThought: "فكرة أخيرة",
    markAsRead: "وضع علامة كمقروء",
    wisdomAcquired: "تم اكتساب الحكمة",
    completedMsg: "لقد أكملت ملخص",
    shareWisdom: "شارك الحكمة",
    nextRead: "القراءة التالية متاحة في",
    volumes: "مجلدات",
    returnHome: "العودة للرئيسية",
    errorMsg: "غير قادر على استرداد حكمة الكتاب في الوقت الحالي. يرجى المحاولة مرة أخرى لاحقًا.",
    brewing: "تحضير حكمتك اليومية...",
    emailPlaceholder: "بريدك@الإلكتروني",
    readSummary: "اقرأ الملخص"
  }
};
